### ISSUE TITLE
Restaurar intro de index y poner logos bien.

### ISSUE THREAD

**Issue by carlosfpardo** [datasketch/mobility-actions#4]
Hola, 
En layouts/index.html yo había escrito al principio una intro nueva que no aparece ahora (volvieron a pegar lo de Mobility works y el subtítulo en español). Pueden porfa restaurarlo @ddazal ? También el orden de los logos está mal. Deben estar arriba solo los de nivel 1 (vean porfa la carpeta de drive con esa numeración) y debajo los de nivel 2. Pero entonces para que sea más claro:
En el primer margen deben ir Datasketch, PBIC y NUMO
En el segundo margen deben ir Epiandes y Streetplans 

También en el footer deben ir Datasketch, PBIC y NUMO (falta PBIC).

Los logos originales (por si acaso) están en https://drive.google.com/drive/folders/1dkCHTghbYzqYzgTZaokwICGMK4riEbxk

**Comment by carlosfpardo** [comment]
Creo que logré resolverlo (texto de líneas 8 y 9 y logos reordenados, falta el de Streetplans) pero mi ignorancia de HTML hace difícil hacerlo bien.

**Comment by ddazal** [comment]
Hola, me perdí. ¿Está resuelto el issue o no? Visita la última versión desplegada para confirmar, por favor https://datasketch.github.io/mobility-actions/

**Comment by carlosfpardo** [comment]
Pues... yo no soy programador pero hice lo posible por restablecer el texto que había escrito y organizar los cuatro logos que había. No sé si haya quedado bien. Tampoco sé cómo agregar el quinto logo. Me avisa usted por favor si hice algo mal? Sin ser programador pero sabiendo qué contenido debe ir trato de ayudarles...

**Comment by carlosfpardo** [comment]
Por si acaso, pego acá lo del mensaje original que todavía falta por arreglar y explico mejor:
- En el primer margen (es decir, arriba) deben ir  NUMO, Datasketch, PBIC. Estas son las tres organizaciones que hicieron más para este trabajo. Esto está casi bien en la versión actual sino que no debería aparecer Epiandes.
- En el segundo margen (es decir, justo debajo) deben ir Epiandes y Streetplans, que son las dos organizaciones que contribuyeron menos. Es decir hay que bajar el de epiandes y poner el de streetplans.
(agrego que, en la misma lógica, el logo de Epiandes no puede aparecer tan grande como está actualmente en la plataforma pues es una de las organizaciones secundarias. Actualmente sale mucho más grande que el de PBIC que es quien dio el 90% de los datos)

Los logos originales (por si acaso) están en https://drive.google.com/drive/folders/1dkCHTghbYzqYzgTZaokwICGMK4riEbxk

Espero haberme sabido explicar, aunque creo que es sencillo.
